"use client";
import { AppButton } from "@/components/ui/AppButton"; import { EmptyState } from "@/components/ui/EmptyState"; import { PageHeader } from "@/components/ui/PageHeader"; import { getBrowserClient } from "@/lib/supabaseBrowser"; import { Heart, Search, Store } from "lucide-react"; import Link from "next/link"; import { FormEvent, useEffect, useState } from "react";
type Supplier = { id:string; name:string; category:string|null; city:string; province:string; region:string; phone:string|null; email:string|null; website:string|null; verification_status:"VERIFIED"|"PROBABLE"|"TO_CHECK"; price_range_min:number|null; price_range_max:number|null; currency:string|null };
type Saved = { id:string; supplier_id:string; status:string; favorite:boolean };
const categories = ["wedding_planner","catering","photographer","videomaker","florist","dj","band","ceremony_music","reception_music","entertainment","decor","lighting","pastry","wedding_cake","favors","invitations","graphic_design","atelier","bride_attire","groom_attire","makeup","hairdresser","car","transfer","rental","babysitting","honeymoon","other"];
export default function SuppliersPage() {
 const [items,setItems]=useState<Supplier[]>([]), [saved,setSaved]=useState<Saved[]>([]), [q,setQ]=useState(""), [category,setCategory]=useState(""), [verification,setVerification]=useState(""), [page,setPage]=useState(1), [pages,setPages]=useState(1), [loading,setLoading]=useState(true);
 async function load(next=page){ setLoading(true); const p=new URLSearchParams({page:String(next),limit:"12"}); if(q)p.set("q",q); if(category)p.set("category",category); if(verification)p.set("verification",verification); const r=await fetch(`/api/suppliers?${p}`); const j=await r.json(); setItems(j.suppliers||[]); setPages(j.pagination?.totalPages||1); setLoading(false); }
 useEffect(()=>{ async function initial(){ const publicRequest=fetch("/api/suppliers?page=1&limit=12").then(r=>r.json()); const {data}=await getBrowserClient().auth.getSession(); const jwt=data.session?.access_token; const privateRequest=jwt?fetch("/api/my/suppliers",{headers:{authorization:`Bearer ${jwt}`}}).then(r=>r.ok?r.json():null):Promise.resolve(null); const [catalog,privateData]=await Promise.all([publicRequest,privateRequest]); setItems(catalog.suppliers||[]); setPages(catalog.pagination?.totalPages||1); setSaved(privateData?.savedSuppliers||[]); setLoading(false); } void initial(); },[]);
 function submit(e:FormEvent){e.preventDefault();setPage(1);void load(1);} const savedBy=(id:string)=>saved.find(s=>s.supplier_id===id);
 async function toggle(id:string){ const current=savedBy(id); const {data}=await getBrowserClient().auth.getSession(); const token=data.session?.access_token; if(!token)return; const r=await fetch(current?`/api/my/suppliers?id=${current.id}`:"/api/my/suppliers",{method:current?"DELETE":"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:current?undefined:JSON.stringify({supplier_id:id})}); if(r.ok){if(current)setSaved(v=>v.filter(s=>s.id!==current.id));else{const j=await r.json();setSaved(v=>[...v,j.savedSupplier]);}} }
 return <section><PageHeader eyebrow="Catalogo globale verificabile" title="Fornitori" description="Cerca professionisti e salva nel tuo evento soltanto le informazioni private sul rapporto con loro." icon={<Store size={24} aria-hidden/>}/>
 <form onSubmit={submit} className="app-card app-card--md mb-6 grid gap-3 md:grid-cols-4"><label className="md:col-span-2"><span className="sr-only">Cerca</span><input className="app-input w-full" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, città, provincia o regione"/></label><select className="app-select" value={category} onChange={e=>setCategory(e.target.value)} aria-label="Categoria"><option value="">Tutte le categorie</option>{categories.map(c=><option key={c}>{c.replaceAll("_"," ")}</option>)}</select><select className="app-select" value={verification} onChange={e=>setVerification(e.target.value)} aria-label="Verifica"><option value="">Ogni verifica</option><option>VERIFIED</option><option>PROBABLE</option><option>TO_CHECK</option></select><AppButton type="submit"><Search size={16}/> Cerca</AppButton></form>
 {loading?<p aria-live="polite">Caricamento…</p>:items.length===0?<EmptyState icon={<Search/>} title="Nessun fornitore trovato" description="Modifica i filtri per ampliare la ricerca."/>:<ul className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(s=><li key={s.id} className="app-card app-card--md"><div className="flex justify-between gap-3"><div><h2 className="font-semibold text-lg">{s.name}</h2>{s.category&&<p className="text-sm capitalize">{s.category.replaceAll("_"," ")}</p>}</div><button onClick={()=>void toggle(s.id)} aria-label={savedBy(s.id)?"Rimuovi dai salvati":"Salva fornitore"} className={savedBy(s.id)?"text-red-600":"text-gray-500"}><Heart fill={savedBy(s.id)?"currentColor":"none"}/></button></div><p className="mt-2 text-sm text-gray-600">{[s.city,s.province,s.region].filter(Boolean).join(", ")}</p><p className="mt-2 text-xs font-semibold">{s.verification_status}</p>{(s.price_range_min!=null||s.price_range_max!=null)&&<p className="text-sm">{s.price_range_min??"—"}–{s.price_range_max??"—"} {s.currency}</p>}<div className="mt-3 flex gap-3 text-sm">{s.phone&&<a href={`tel:${s.phone}`}>Telefono</a>}{s.email&&<a href={`mailto:${s.email}`}>Email</a>}{s.website&&<a href={s.website} target="_blank" rel="noreferrer">Sito</a>}<Link href={`fornitori/${s.id}`}>Dettaglio</Link></div></li>)}</ul>}
 <div className="mt-6 flex items-center justify-center gap-3"><AppButton variant="outline" disabled={page<=1} onClick={()=>{const n=page-1;setPage(n);void load(n)}}>Precedente</AppButton><span>{page}/{pages}</span><AppButton variant="outline" disabled={page>=pages} onClick={()=>{const n=page+1;setPage(n);void load(n)}}>Successiva</AppButton></div></section>;
}
