"use client";
import { FormEvent,useEffect,useState } from "react";
import { AppButton } from "@/components/ui/AppButton";
import { AppCard } from "@/components/ui/AppCard";
import { getIntlLocale } from "@/i18n/localeFormat";
import { getBrowserClient } from "@/lib/supabaseBrowser";
import { LOCATION_TYPES,PLACE_TYPES,SUPPLIER_TYPES } from "@/lib/catalogContributions";
import type { CatalogEntityType } from "@/lib/catalogSearch";
import { useLocale,useTranslations } from "next-intl";
type Submission={id:string;entity_type:CatalogEntityType;payload:{name:string;type:string};status:string;created_at:string};
export default function ContributionPanel({entityType,eventId,initialData}:{entityType:CatalogEntityType;eventId?:string;initialData?:Record<string,string>}){
 const t=useTranslations("communityContributions"),locale=useLocale();
 const [open,setOpen]=useState(false),[mine,setMine]=useState<Submission[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [form,setForm]=useState({name:initialData?.name||"",type:"",custom_type:"",city:initialData?.city||"",province:initialData?.province||"",region:initialData?.region||"",country:"it",address:initialData?.address||"",postal_code:"",website:"",phone:"",email:"",reviewer_notes:""});
 const types=entityType==="church"?PLACE_TYPES:entityType==="location"?LOCATION_TYPES:SUPPLIER_TYPES;
 const typeLabel=(value:string)=>t.has(`types.${value}`)?t(`types.${value}`):value;
 const statusLabel=(value:string)=>t.has(`statuses.${value}`)?t(`statuses.${value}`):value;
 async function token(){return (await getBrowserClient().auth.getSession()).data.session?.access_token;}
 async function load(){const jwt=await token();if(!jwt)return;const r=await fetch("/api/catalog/contributions",{headers:{authorization:`Bearer ${jwt}`},cache:"no-store"});if(r.ok){const j=await r.json();setMine((j.submissions||[]).filter((s:Submission)=>s.entity_type===entityType));}}
 // Initial authenticated read; state changes happen only after the external request resolves.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void load();},[entityType]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const jwt=await token();if(!jwt){setMessage(t("messages.authRequired"));setBusy(false);return;}const r=await fetch("/api/catalog/contributions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${jwt}`},body:JSON.stringify({entity_type:entityType,event_id:eventId,data:form})});const j=await r.json();if(r.status===409&&j.error==="DUPLICATE_LIKELY"){setMessage(t("messages.duplicate",{name:j.duplicates?.[0]?.name||""}));}else if(!r.ok)setMessage(j.error==="RATE_LIMITED"?t("messages.rateLimited"):t("messages.submitError"));else{setMessage(t("messages.submitted"));setOpen(false);void load();}setBusy(false);}
 return <div className="space-y-4"><AppButton variant="outline" onClick={()=>setOpen(v=>!v)}>+ {t(`add.${entityType}`)}</AppButton>
 {open?<AppCard><form onSubmit={submit} className="grid min-w-0 gap-4 sm:grid-cols-2"><h2 className="text-xl font-bold sm:col-span-2">{t(`form.heading.${entityType}`)}</h2><Field label={t("form.name")}><input required className="app-input w-full" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label={t("form.type")}><select required className="app-select w-full" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="">{t("form.select")}</option>{types.map(v=><option key={v} value={v}>{typeLabel(v)}</option>)}</select></Field>{entityType==="supplier"&&form.type==="other"?<Field label={t("form.customType")}><input required className="app-input w-full" value={form.custom_type} onChange={e=>setForm({...form,custom_type:e.target.value})}/></Field>:null}<Field label={t("form.city")}><input required className="app-input w-full" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Field><Field label={t("form.province")}><input required className="app-input w-full" value={form.province} onChange={e=>setForm({...form,province:e.target.value})}/></Field><Field label={t("form.region")}><input required className="app-input w-full" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></Field><Field label={t("form.country")}><input required maxLength={2} className="app-input w-full" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></Field><Field label={t("form.address")}><input className="app-input w-full" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label={t("form.postalCode")}><input className="app-input w-full" value={form.postal_code} onChange={e=>setForm({...form,postal_code:e.target.value})}/></Field><Field label={t("form.website")}><input type="url" className="app-input w-full" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></Field><Field label={t("form.phone")}><input type="tel" className="app-input w-full" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label={t("form.email")}><input type="email" className="app-input w-full" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label={t("form.reviewerNotes")}><textarea className="app-input min-h-24 w-full" value={form.reviewer_notes} onChange={e=>setForm({...form,reviewer_notes:e.target.value})}/></Field><div className="flex flex-wrap gap-2 sm:col-span-2"><AppButton type="submit" loading={busy}>{t("form.submit")}</AppButton><AppButton type="button" variant="ghost" onClick={()=>setOpen(false)}>{t("form.cancel")}</AppButton></div></form></AppCard>:null}
 {message?<p role="status" aria-live="polite" className="text-sm">{message}</p>:null}{mine.length?<AppCard><h2 className="font-bold">{t("mine")}</h2><ul className="mt-3 divide-y">{mine.map(s=><li key={s.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span><strong>{s.payload.name}</strong> · {typeLabel(s.payload.type)}</span><span>{new Date(s.created_at).toLocaleDateString(getIntlLocale(locale))} · {statusLabel(s.status)}</span></li>)}</ul></AppCard>:null}</div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="min-w-0 space-y-1 text-sm font-semibold"><span>{label}</span>{children}</label>}
