"use client";
import { FormEvent,useEffect,useState } from "react";
import { AppButton } from "@/components/ui/AppButton";
import { AppCard } from "@/components/ui/AppCard";
import { getBrowserClient } from "@/lib/supabaseBrowser";
import { LOCATION_TYPES,PLACE_TYPES,SUPPLIER_TYPES } from "@/lib/catalogContributions";
import type { CatalogEntityType } from "@/lib/catalogSearch";
type Submission={id:string;entity_type:CatalogEntityType;payload:{name:string;type:string};status:string;created_at:string};
const labels:Record<string,string>={church:"Luogo",location:"Location",supplier:"Fornitore",PENDING:"In verifica",APPROVED:"Approvata",REJECTED:"Non approvata",NEEDS_CHANGES:"Da completare"};
const typeLabels:Record<string,string>={church:"Chiesa",basilica:"Basilica",cathedral:"Cattedrale",abbey:"Abbazia",sanctuary:"Santuario",chapel:"Cappella",mosque:"Moschea",synagogue:"Sinagoga",temple:"Tempio",place_of_worship:"Altro luogo di culto",ceremony_place:"Altro luogo pertinente alla cerimonia",reception_restaurant:"Ristorante per ricevimenti",villa:"Villa",reception_hall:"Sala ricevimenti",event_hotel:"Hotel con eventi",resort:"Resort",agriturismo:"Agriturismo",castle_historic_house:"Castello / dimora storica",estate:"Tenuta",masseria:"Masseria",event_venue:"Location eventi",seaside_venue:"Struttura sul mare",photographer:"Fotografo",videomaker:"Videomaker",florist:"Fiorista",wedding_planner:"Wedding Planner",makeup_artist:"Make-up Artist",hair_stylist:"Hair Stylist",music:"Musica",dj:"DJ",entertainment:"Intrattenimento",transport:"Trasporti",atelier:"Atelier",favors:"Bomboniere",catering:"Catering",bakery:"Pasticceria",rental:"Noleggio",lighting:"Luci",other:"Altro"};
export default function ContributionPanel({entityType,eventId,initialData}:{entityType:CatalogEntityType;eventId?:string;initialData?:Record<string,string>}){
 const [open,setOpen]=useState(false),[mine,setMine]=useState<Submission[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [form,setForm]=useState({name:initialData?.name||"",type:"",custom_type:"",city:initialData?.city||"",province:initialData?.province||"",region:initialData?.region||"",country:"it",address:initialData?.address||"",postal_code:"",website:"",phone:"",email:"",reviewer_notes:""});
 const types=entityType==="church"?PLACE_TYPES:entityType==="location"?LOCATION_TYPES:SUPPLIER_TYPES;
 async function token(){return (await getBrowserClient().auth.getSession()).data.session?.access_token;}
 async function load(){const jwt=await token();if(!jwt)return;const r=await fetch("/api/catalog/contributions",{headers:{authorization:`Bearer ${jwt}`},cache:"no-store"});if(r.ok){const j=await r.json();setMine((j.submissions||[]).filter((s:Submission)=>s.entity_type===entityType));}}
 // Initial authenticated read; state changes happen only after the external request resolves.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void load();},[entityType]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const jwt=await token();if(!jwt){setMessage("Accedi per inviare una proposta.");setBusy(false);return;}const r=await fetch("/api/catalog/contributions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${jwt}`},body:JSON.stringify({entity_type:entityType,event_id:eventId,data:form})});const j=await r.json();if(r.status===409&&j.error==="DUPLICATE_LIKELY"){setMessage(`Potrebbe essere già presente nel catalogo: ${j.duplicates?.[0]?.name}. Verifica il risultato prima di continuare.`);}else if(!r.ok)setMessage(j.error==="RATE_LIMITED"?"Hai inviato troppe proposte in poco tempo. Riprova tra un minuto.":"Non è stato possibile inviare la proposta.");else{setMessage("Proposta inviata. La controlleremo prima della pubblicazione.");setOpen(false);void load();}setBusy(false);}
 return <div className="space-y-4"><AppButton variant="outline" onClick={()=>setOpen(v=>!v)}>+ {entityType==="church"?"Aggiungi un luogo":entityType==="location"?"Aggiungi una location":"Aggiungi un fornitore"}</AppButton>
 {open?<AppCard><form onSubmit={submit} className="grid min-w-0 gap-4 sm:grid-cols-2"><h2 className="text-xl font-bold sm:col-span-2">Proponi {labels[entityType].toLowerCase()} al catalogo</h2><Field label="Nome *"><input required className="app-input w-full" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Tipologia *"><select required className="app-select w-full" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="">Seleziona</option>{types.map(v=><option key={v} value={v}>{typeLabels[v]||v}</option>)}</select></Field>{entityType==="supplier"&&form.type==="other"?<Field label="Descrivi il tipo *"><input required className="app-input w-full" value={form.custom_type} onChange={e=>setForm({...form,custom_type:e.target.value})}/></Field>:null}<Field label="Comune *"><input required className="app-input w-full" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Field><Field label="Provincia *"><input required className="app-input w-full" value={form.province} onChange={e=>setForm({...form,province:e.target.value})}/></Field><Field label="Regione *"><input required className="app-input w-full" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></Field><Field label="Paese *"><input required maxLength={2} className="app-input w-full" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></Field><Field label="Indirizzo"><input className="app-input w-full" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field><Field label="CAP"><input className="app-input w-full" value={form.postal_code} onChange={e=>setForm({...form,postal_code:e.target.value})}/></Field><Field label="Sito ufficiale"><input type="url" className="app-input w-full" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></Field><Field label="Telefono"><input type="tel" className="app-input w-full" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email"><input type="email" className="app-input w-full" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Note per il revisore"><textarea className="app-input min-h-24 w-full" value={form.reviewer_notes} onChange={e=>setForm({...form,reviewer_notes:e.target.value})}/></Field><div className="flex flex-wrap gap-2 sm:col-span-2"><AppButton type="submit" loading={busy}>Invia proposta</AppButton><AppButton type="button" variant="ghost" onClick={()=>setOpen(false)}>Annulla</AppButton></div></form></AppCard>:null}
 {message?<p role="status" aria-live="polite" className="text-sm">{message}</p>:null}{mine.length?<AppCard><h2 className="font-bold">Le mie proposte</h2><ul className="mt-3 divide-y">{mine.map(s=><li key={s.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span><strong>{s.payload.name}</strong> · {typeLabels[s.payload.type]||s.payload.type}</span><span>{new Date(s.created_at).toLocaleDateString("it-IT")} · {labels[s.status]||s.status}</span></li>)}</ul></AppCard>:null}</div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="min-w-0 space-y-1 text-sm font-semibold"><span>{label}</span>{children}</label>}
