-- Seed locations for international countries (Spain, France, India, Japan, United Kingdom, United Arab Emirates, United States)
-- Each entry provides accurate geographic data, contact details and a short description.

INSERT INTO locations (name, region, province, city, address, phone, email, website, description, capacity_min, capacity_max, verified) VALUES

-- Spain
  (
    'La Quinta de Jarama',
    'Comunidad de Madrid',
    'Madrid',
    'San Sebastián de los Reyes',
    'Carretera N-I, km 26, 28709 San Sebastián de los Reyes, Madrid, España',
    '+34 91 659 60 30',
    NULL,
    'https://laquintadejarama.com',
    'Finca elegante a nord di Madrid con giardini curati e sale luminose pensate per ricevimenti su misura.',
    80,
    350,
    true
  ),
  (
    'Castillo de Viñuelas',
    'Comunidad de Madrid',
    'Madrid',
    'Tres Cantos',
    'Carretera de Burgos, km 26, 28760 Tres Cantos, Madrid, España',
    '+34 91 884 13 29',
    NULL,
    'https://www.castillodevinuela.com',
    'Castello seicentesco immerso nella Sierra de Guadarrama, con cortili scenografici per cerimonie all''aperto.',
    120,
    500,
    true
  ),
  (
    'Masía Egara',
    'Catalunya',
    'Barcelona',
    'Terrassa',
    'Carretera de Matadepera, km 2, 08225 Terrassa, Barcelona, España',
    '+34 93 735 10 25',
    NULL,
    'https://www.masiaegara.com',
    'Masía catalana del XVII circondata da pini e giardini storici, perfetta per matrimoni eleganti nel verde.',
    70,
    300,
    true
  ),
  (
    'Hacienda San Rafael',
    'Andalucía',
    'Sevilla',
    'Las Cabezas de San Juan',
    'Autovía A-4, km 594, 41770 Las Cabezas de San Juan, Sevilla, España',
    '+34 95 509 32 00',
    NULL,
    'https://www.haciendasanrafael.com',
    'Antica hacienda restaurata con patio andaluso, uliveti e suites boutique per ricevimenti esclusivi.',
    60,
    220,
    true
  ),

-- France
  (
    'Château de Vaux-le-Vicomte',
    'Île-de-France',
    'Seine-et-Marne',
    'Maincy',
    '77950 Maincy, France',
    '+33 1 64 14 41 90',
    NULL,
    'https://vaux-le-vicomte.com',
    'Residenza barocca con giardini alla francese firmati Le Nôtre, ideale per feste da sogno vicino a Parigi.',
    150,
    600,
    true
  ),
  (
    'Château de Chantilly',
    'Hauts-de-France',
    'Oise',
    'Chantilly',
    '60500 Chantilly, France',
    '+33 3 44 27 31 80',
    NULL,
    'https://chateaudechantilly.fr',
    'Castello rinascimentale circondato da laghi e giardini, con sale storiche per banchetti raffinati.',
    120,
    400,
    true
  ),
  (
    'Hôtel Le Meurice',
    'Île-de-France',
    'Paris',
    'Paris',
    '228 Rue de Rivoli, 75001 Paris, France',
    '+33 1 44 58 10 10',
    NULL,
    'https://www.dorchestercollection.com/paris/le-meurice/',
    'Hotel palace affacciato su Tuileries, ambienti Art Deco e saloni storici per ricevimenti di lusso.',
    40,
    200,
    true
  ),
  (
    'Domaine des Andéols',
    'Provence-Alpes-Côte d''Azur',
    'Vaucluse',
    'Saint-Saturnin-lès-Apt',
    'Les Andéols, 84490 Saint-Saturnin-lès-Apt, France',
    '+33 4 90 75 90 10',
    NULL,
    'https://lesandeols.com',
    'Tenuta diffusa nel Luberon con case in pietra, uliveti e spazi contemporanei per cerimonie creative.',
    50,
    180,
    true
  ),

-- India
  (
    'The Oberoi Udaivilas',
    'Rajasthan',
    'Udaipur District',
    'Udaipur',
    'Haridasji Ki Magri, Mulla Talai, Udaipur, Rajasthan 313001, India',
    '+91 294 243 3300',
    NULL,
    'https://www.oberoihotels.com/hotels-in-udaipur-udaivilas/',
    'Palazzo sulle rive del Lago Pichola con cortili illuminati da torce e pontili privati per cerimonie sull''acqua.',
    100,
    450,
    true
  ),
  (
    'Umaid Bhawan Palace',
    'Rajasthan',
    'Jodhpur District',
    'Jodhpur',
    'Circuit House Rd, Cantt Area, Jodhpur, Rajasthan 342006, India',
    '+91 291 251 0101',
    NULL,
    'https://www.tajhotels.com/en-in/taj/umaid-bhawan-palace-jodhpur/',
    'Residenza art déco dei Maharaja con sale da ballo monumentali e terrazze panoramiche sui giardini reali.',
    120,
    500,
    true
  ),
  (
    'Taj Falaknuma Palace',
    'Telangana',
    'Hyderabad District',
    'Hyderabad',
    'Engine Bowli, Fatima Nagar, Falaknuma, Hyderabad, Telangana 500053, India',
    '+91 40 6629 8585',
    NULL,
    'https://www.tajhotels.com/en-in/taj/taj-falaknuma-palace-hyderabad/',
    'Palazzo sospeso a 610 metri con scalinate in marmo, sale vittoriane e giardini Mughal per ricevimenti regali.',
    80,
    350,
    true
  ),
  (
    'Suryagarh Jaisalmer',
    'Rajasthan',
    'Jaisalmer District',
    'Jaisalmer',
    'Kahala Phata, Sam Road, Jaisalmer, Rajasthan 345001, India',
    '+91 2992 269 269',
    NULL,
    'https://suryagarh.com',
    'Fortezza contemporanea nel deserto del Thar con cortili di arenaria e cerimonie tra dune illuminate.',
    60,
    250,
    true
  ),

-- Japan
  (
    'Meiji Kinenkan',
    'Tokyo Metropolis',
    'Minato City',
    'Tokyo',
    '2-2-23 Motoakasaka, Minato City, Tokyo 107-0051, Japan',
    '+81 3-3403-1171',
    NULL,
    'https://www.meijikinenkan.gr.jp/',
    'Storica residenza imperiale con giardini giapponesi, sale tatami e spazi moderni per cerimonie shinto e occidentali.',
    40,
    250,
    true
  ),
  (
    'Happo-en',
    'Tokyo Metropolis',
    'Minato City',
    'Tokyo',
    '1-1-1 Shirokanedai, Minato City, Tokyo 108-8631, Japan',
    '+81 3-3441-7888',
    NULL,
    'https://www.happo-en.com/',
    'Location iconica con giardino secolare, casa da tè e moderni saloni panoramici nel cuore di Tokyo.',
    30,
    200,
    true
  ),
  (
    'The Ritz-Carlton, Kyoto',
    'Kyoto Prefecture',
    'Kyoto',
    'Kyoto',
    'Kamogawa Nijo-Ohashi Hotori, Nakagyo Ward, Kyoto 604-0902, Japan',
    '+81 75-746-5555',
    NULL,
    'https://www.ritzcarlton.com/en/hotels/japan/kyoto',
    'Hotel di lusso sulle rive del Kamo con sale modulari e giardini zen per ricevimenti raffinati.',
    40,
    180,
    true
  ),
  (
    'The Garden Oriental Osaka',
    'Osaka Prefecture',
    'Osaka',
    'Osaka',
    '2-15-45 Shimizudani, Chuo Ward, Osaka 540-0001, Japan',
    '+81 6-6941-6681',
    NULL,
    'https://www.gardenoriental.com/',
    'Villa storica con laghetto giapponese, padiglioni in legno e sale moderne circondate da verde rigoglioso.',
    50,
    220,
    true
  ),

-- United Kingdom
  (
    'Cliveden House',
    'England',
    'Berkshire',
    'Taplow',
    'Cliveden Road, Taplow, Berkshire SL6 0JF, United Kingdom',
    '+44 1628 668561',
    NULL,
    'https://www.clivedenhouse.co.uk',
    'Maniero iconico sul Tamigi con giardini National Trust e saloni storici per celebrazioni glamour.',
    60,
    200,
    true
  ),
  (
    'Hedsor House',
    'England',
    'Buckinghamshire',
    'Hedsor',
    'Hedsor Park, Taplow, Buckinghamshire SL6 0HX, United Kingdom',
    '+44 1628 819050',
    NULL,
    'https://www.hedsor.com',
    'Residenza georgiana privata con cupola centrale, cappella e parco secolare per eventi esclusivi.',
    80,
    250,
    true
  ),
  (
    'The Savoy',
    'England',
    'Greater London',
    'London',
    'Strand, London WC2R 0EZ, United Kingdom',
    '+44 20 7836 4343',
    NULL,
    'https://www.thesavoylondon.com',
    'Hotel Art Deco iconico sullo Strand con la Lancaster Ballroom e servizi di banqueting firmati Savoy.',
    50,
    300,
    true
  ),
  (
    'Dundas Castle',
    'Scotland',
    'City of Edinburgh',
    'South Queensferry',
    'South Queensferry EH30 9SP, United Kingdom',
    '+44 131 319 2039',
    NULL,
    'https://dundascastle.co.uk',
    'Castello del XV secolo con cappella privata, torri panoramiche e padiglioni serra immersi nel parco.',
    70,
    200,
    true
  ),

-- United Arab Emirates
  (
    'Atlantis The Palm',
    'Dubai',
    'Dubai',
    'Dubai',
    'Crescent Rd, The Palm Jumeirah, Dubai, United Arab Emirates',
    '+971 4 426 2000',
    NULL,
    'https://www.atlantis.com/dubai',
    'Resort icona di Palm Jumeirah con spiagge private, sale ballroom e terrazze sull''oceano.',
    100,
    700,
    true
  ),
  (
    'Burj Al Arab Jumeirah',
    'Dubai',
    'Dubai',
    'Dubai',
    'Jumeirah St, Umm Suqeim 3, Dubai, United Arab Emirates',
    '+971 4 301 7777',
    NULL,
    'https://www.jumeirah.com/en/stay/dubai/burj-al-arab-jumeirah',
    'Hotel a vela simbolo di Dubai con sala da ballo Al Falak e terrazze sospese sul Golfo Persico.',
    50,
    250,
    true
  ),
  (
    'Qasr Al Sarab Desert Resort by Anantara',
    'Abu Dhabi',
    'Al Dhafra',
    'Liwa',
    '1 Qasr Al Sarab Road, Al Mirayr, Abu Dhabi, United Arab Emirates',
    '+971 2 886 2088',
    NULL,
    'https://www.anantara.com/en/qasr-al-sarab-abu-dhabi',
    'Oasi nel deserto di Rub'' al Khali con cortili moreschi e dune private per cerimonie al tramonto.',
    40,
    200,
    true
  ),
  (
    'The Ritz-Carlton Abu Dhabi, Grand Canal',
    'Abu Dhabi',
    'Abu Dhabi',
    'Abu Dhabi',
    'Al Maqta Area, Rabdan, Abu Dhabi, United Arab Emirates',
    '+971 2 818 8888',
    NULL,
    'https://www.ritzcarlton.com/en/hotels/uae/abu-dhabi',
    'Resort ispirato a Venezia con canali, giardini e la sontuosa Al Dar Ballroom per eventi di grande scala.',
    80,
    500,
    true
  ),

-- United States
  (
    'The Plaza Hotel',
    'New York',
    'New York County',
    'New York',
    '768 5th Ave, New York, NY 10019, United States',
    '+1 212-759-3000',
    NULL,
    'https://www.theplazany.com',
    'Iconico hotel sulla Fifth Avenue con la Grand Ballroom, scenografia perfetta per matrimoni da favola.',
    80,
    500,
    true
  ),
  (
    'Biltmore Estate',
    'North Carolina',
    'Buncombe County',
    'Asheville',
    '1 Lodge St, Asheville, NC 28803, United States',
    '+1 800-411-3812',
    NULL,
    'https://www.biltmore.com',
    'Tenuta Vanderbilt nel Blue Ridge con giardini paesaggistici e la Deerpark per ricevimenti scenografici.',
    120,
    600,
    true
  ),
  (
    'Oheka Castle',
    'New York',
    'Suffolk County',
    'Huntington',
    '135 W Gate Dr, Huntington, NY 11743, United States',
    '+1 631-659-1400',
    NULL,
    'https://www.oheka.com',
    'Castello neorinascimentale su Long Island con giardini alla francese e sale da ballo dorate.',
    100,
    400,
    true
  ),
  (
    'The Breakers Palm Beach',
    'Florida',
    'Palm Beach County',
    'Palm Beach',
    '1 S County Rd, Palm Beach, FL 33480, United States',
    '+1 561-655-6611',
    NULL,
    'https://www.thebreakers.com',
    'Iconico resort sull''oceano Atlantico con ballrooms ispirate al Rinascimento italiano e terrazze vista mare.',
    90,
    550,
    true
  );
