import { NextRequest,NextResponse } from "next/server";
import { requireUser } from "@/lib/apiAuth";
import { checkAuthRateLimit } from "@/lib/authRateLimit";
import { contributionFingerprint,findDuplicates,parseContribution } from "@/lib/catalogContributions";
import { getServiceClient } from "@/lib/supabaseServer";
import type { CatalogEntityType } from "@/lib/catalogSearch";
export const runtime="nodejs";
function fail(error:unknown){const message=error instanceof Error?error.message:"UNKNOWN";const status=/JWT|Bearer/.test(message)?401:message==="FORBIDDEN"?403:400;return NextResponse.json({error:message},{status});}
export async function GET(req:NextRequest){try{const {userId}=await requireUser(req);const db=getServiceClient();const {data,error}=await db.from("catalog_review_queue").select("id,entity_type,payload,status,created_at,updated_at,user_message,canonical_record_id").eq("source","user_submission").eq("submitted_by",userId).order("created_at",{ascending:false});if(error)throw error;return NextResponse.json({submissions:data});}catch(e){return fail(e);}}
export async function POST(req:NextRequest){try{const {userId}=await requireUser(req);const minute=await checkAuthRateLimit(req,`catalog-submit-minute:${userId}`,5);if(!minute.allowed)return NextResponse.json({error:"RATE_LIMITED"},{status:429});const daily=await checkAuthRateLimit(req,`catalog-submit-day:${userId}`,20,86400);if(!daily.allowed)return NextResponse.json({error:"DAILY_LIMIT_REACHED"},{status:429});const body=await req.json() as Record<string,unknown>;const entityType=body.entity_type as CatalogEntityType;if(!["church","location","supplier"].includes(entityType))throw new Error("INVALID_ENTITY_TYPE");const proposed=parseContribution(entityType,body.data);const duplicates=await findDuplicates(entityType,proposed);if(duplicates[0]?.score>=90&&!body.duplicate_override)return NextResponse.json({error:"DUPLICATE_LIKELY",duplicates},{status:409});const fingerprint=contributionFingerprint(entityType,proposed);const db=getServiceClient();if(typeof body.event_id==="string"){const {data:owned}=await db.from("events").select("id").eq("id",body.event_id).eq("owner_id",userId).maybeSingle();if(!owned)throw new Error("INVALID_EVENT");}const {data:repeat}=await db.from("catalog_review_queue").select("id,status").eq("source","user_submission").eq("submitted_by",userId).eq("incoming_fingerprint",fingerprint).in("status",["PENDING","NEEDS_CHANGES","APPROVED"]).maybeSingle();if(repeat)return NextResponse.json({error:"ALREADY_SUBMITTED",submission:repeat},{status:409});const top=duplicates[0];const {data,error}=await db.from("catalog_review_queue").insert({entity_type:entityType,candidate_entity_id:top?.id||null,source:"user_submission",incoming_fingerprint:fingerprint,match_score:top?.score||0,conflict_level:top?"SOFT_CONFLICT":"NON_CONFLICTING",reasons:{duplicate_override:Boolean(body.duplicate_override)},payload:proposed,status:"PENDING",submitted_by:userId,event_id:typeof body.event_id==="string"?body.event_id:null}).select("id,entity_type,payload,status,created_at").single();if(error)throw error;return NextResponse.json({submission:data,duplicates},{status:201});}catch(e){return fail(e);}}
export async function PATCH(req:NextRequest){try{const {userId}=await requireUser(req);const body=await req.json() as Record<string,unknown>;const entityType=body.entity_type as CatalogEntityType;const proposed=parseContribution(entityType,body.data);const db=getServiceClient();const {data,error}=await db.from("catalog_review_queue").update({payload:proposed,incoming_fingerprint:contributionFingerprint(entityType,proposed),status:"PENDING",updated_at:new Date().toISOString(),reviewed_at:null,reviewed_by:null,user_message:null}).eq("id",String(body.id)).eq("submitted_by",userId).in("status",["PENDING","NEEDS_CHANGES"]).select("id,status").maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:"NOT_FOUND"},{status:404});return NextResponse.json({submission:data});}catch(e){return fail(e);}}
