"use client";
import { useEffect,useState } from "react";
import { getBrowserClient } from "@/lib/supabaseBrowser";
import { AppButton } from "@/components/ui/AppButton";
import { AppCard } from "@/components/ui/AppCard";
import { PageHeader } from "@/components/ui/PageHeader";
import { ShieldCheck } from "lucide-react";
type Item={id:string;entity_type:string;payload:Record<string,string>;status:string;created_at:string;match_score:number;candidate_entity_id:string|null;user_message:string|null};
export default function ModerationPage(){const [items,setItems]=useState<Item[]>([]),[entity,setEntity]=useState(""),[status,setStatus]=useState("PENDING"),[error,setError]=useState(""),[busy,setBusy]=useState("");
 async function auth(){return (await getBrowserClient().auth.getSession()).data.session?.access_token;}
 async function load(){const token=await auth();if(!token){setError("Accesso richiesto.");return;}const p=new URLSearchParams();if(entity)p.set("entity_type",entity);if(status)p.set("status",status);const r=await fetch(`/api/admin/catalog-moderation?${p}`,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});if(r.status===403){setError("Area riservata agli amministratori.");return;}const j=await r.json();if(!r.ok){setError("Impossibile caricare la coda.");return;}setError("");setItems(j.submissions||[]);}
 // Filters intentionally trigger a fresh server-authorized queue read.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void load();},[entity,status]);
 async function act(item:Item,action:string){const token=await auth();if(!token)return;let canonical_record_id:string|null=null,user_message:string|null=null;if(action==="MERGE")canonical_record_id=window.prompt("ID del record esistente")||null;if(action==="REJECT"||action==="NEEDS_CHANGES")user_message=window.prompt("Messaggio visibile all'utente (facoltativo)")||null;if(action==="APPROVE"&&!window.confirm("Pubblicare questa proposta nel catalogo?"))return;setBusy(item.id);const r=await fetch("/api/admin/catalog-moderation",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({id:item.id,action,entity_type:item.entity_type,data:item.payload,canonical_record_id,user_message,confirm_duplicate:action==="MERGE"})});const j=await r.json();if(!r.ok)setError(j.error||"Operazione non riuscita");else await load();setBusy("");}
 return <section className="space-y-6"><PageHeader eyebrow="Area amministrativa" title="Moderazione catalogo" description="Controlla le proposte prima della pubblicazione." icon={<ShieldCheck aria-hidden/>}/><div className="flex flex-wrap gap-3"><select className="app-select" value={entity} onChange={e=>setEntity(e.target.value)} aria-label="Tipo"><option value="">Tutti i tipi</option><option value="church">Luoghi</option><option value="location">Location</option><option value="supplier">Fornitori</option></select><select className="app-select" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Stato"><option value="PENDING">In verifica</option><option value="APPROVED">Approvati</option><option value="REJECTED">Rifiutati</option><option value="NEEDS_CHANGES">Da completare</option></select></div>{error?<AppCard><p role="alert" className="text-red-700">{error}</p></AppCard>:null}<div className="grid gap-4">{items.map(i=><AppCard key={i.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-bold uppercase">{i.entity_type} · {i.status}</p><h2 className="text-lg font-bold">{i.payload.name}</h2><p className="text-sm">{i.payload.type} · {[i.payload.city,i.payload.province,i.payload.region,i.payload.country?.toUpperCase()].filter(Boolean).join(", ")}</p>{i.payload.address?<p className="text-sm">{i.payload.address}</p>:null}{i.payload.reviewer_notes?<p className="mt-2 text-sm"><strong>Note:</strong> {i.payload.reviewer_notes}</p>:null}{i.candidate_entity_id?<p className="mt-2 text-sm text-amber-800">Possibile duplicato: {i.candidate_entity_id} (score {i.match_score})</p>:null}</div><time className="text-sm">{new Date(i.created_at).toLocaleDateString("it-IT")}</time></div>{i.status==="PENDING"||i.status==="NEEDS_CHANGES"?<div className="mt-4 flex flex-wrap gap-2"><AppButton loading={busy===i.id} onClick={()=>void act(i,"APPROVE")}>Approva</AppButton><AppButton variant="outline" onClick={()=>void act(i,"MERGE")}>Approva e collega</AppButton><AppButton variant="outline" onClick={()=>void act(i,"NEEDS_CHANGES")}>Richiedi modifica</AppButton><AppButton variant="ghost" onClick={()=>void act(i,"REJECT")}>Rifiuta</AppButton></div>:null}</AppCard>)}</div>{!error&&items.length===0?<AppCard><p>Nessuna proposta per questi filtri.</p></AppCard>:null}</section>}
