"use client";
import { useEffect,useState } from "react";
import { getBrowserClient } from "@/lib/supabaseBrowser";
import { AppButton } from "@/components/ui/AppButton";
import { AppCard } from "@/components/ui/AppCard";
import { PageHeader } from "@/components/ui/PageHeader";
import { getIntlLocale } from "@/i18n/localeFormat";
import { ShieldCheck } from "lucide-react";
import { useLocale,useTranslations } from "next-intl";
type Item={id:string;entity_type:string;payload:Record<string,string>;status:string;created_at:string;match_score:number;candidate_entity_id:string|null;user_message:string|null};
export default function ModerationPage(){const t=useTranslations("catalogModeration"),tc=useTranslations("communityContributions"),locale=useLocale();const [items,setItems]=useState<Item[]>([]),[entity,setEntity]=useState(""),[status,setStatus]=useState("PENDING"),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const label=(group:string,value:string)=>t.has(`${group}.${value}`)?t(`${group}.${value}`):value;
 const typeLabel=(value:string)=>tc.has(`types.${value}`)?tc(`types.${value}`):value;
 async function auth(){return (await getBrowserClient().auth.getSession()).data.session?.access_token;}
 async function load(){const token=await auth();if(!token){setError(t("errors.auth"));return;}const p=new URLSearchParams();if(entity)p.set("entity_type",entity);if(status)p.set("status",status);const r=await fetch(`/api/admin/catalog-moderation?${p}`,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});if(r.status===403){setError(t("errors.adminOnly"));return;}const j=await r.json();if(!r.ok){setError(t("errors.load"));return;}setError("");setItems(j.submissions||[]);}
 // Filters intentionally trigger a fresh server-authorized queue read.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void load();},[entity,status]);
 async function act(item:Item,requestedAction:string){const token=await auth();if(!token)return;let action=requestedAction;let data={...item.payload};let canonical_record_id:string|null=null,user_message:string|null=null;if(action==="EDIT_APPROVE"){const name=window.prompt(t("prompts.canonicalName"),data.name);if(name===null)return;const type=window.prompt(t("prompts.canonicalType"),data.type);if(type===null)return;const city=window.prompt(t("prompts.city"),data.city);if(city===null)return;data={...data,name,type,city};action="APPROVE";}if(action==="MERGE")canonical_record_id=window.prompt(t("prompts.recordId"))||null;if(action==="REJECT"||action==="NEEDS_CHANGES")user_message=window.prompt(t("prompts.userMessage"))||null;if(action==="APPROVE"&&!window.confirm(t("confirmApprove")))return;setBusy(item.id);const r=await fetch("/api/admin/catalog-moderation",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({id:item.id,action,entity_type:item.entity_type,data,canonical_record_id,user_message,confirm_duplicate:action==="MERGE"})});if(!r.ok)setError(t("errors.action"));else await load();setBusy("");}
 return <section className="space-y-6"><PageHeader eyebrow={t("eyebrow")} title={t("title")} description={t("description")} icon={<ShieldCheck aria-hidden/>}/><div className="flex flex-wrap gap-3"><select className="app-select" value={entity} onChange={e=>setEntity(e.target.value)} aria-label={t("filters.typeAria")}><option value="">{t("filters.allTypes")}</option><option value="church">{t("entities.church")}</option><option value="location">{t("entities.location")}</option><option value="supplier">{t("entities.supplier")}</option></select><select className="app-select" value={status} onChange={e=>setStatus(e.target.value)} aria-label={t("filters.statusAria")}><option value="PENDING">{t("statuses.PENDING")}</option><option value="APPROVED">{t("statuses.APPROVED")}</option><option value="REJECTED">{t("statuses.REJECTED")}</option><option value="NEEDS_CHANGES">{t("statuses.NEEDS_CHANGES")}</option></select></div>{error?<AppCard><p role="alert" className="text-red-700">{error}</p></AppCard>:null}<div className="grid gap-4">{items.map(i=><AppCard key={i.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-bold uppercase">{label("entities",i.entity_type)} · {label("statuses",i.status)}</p><h2 className="text-lg font-bold">{i.payload.name}</h2><p className="text-sm">{typeLabel(i.payload.type)} · {[i.payload.city,i.payload.province,i.payload.region,i.payload.country?.toUpperCase()].filter(Boolean).join(", ")}</p>{i.payload.address?<p className="text-sm">{i.payload.address}</p>:null}{i.payload.reviewer_notes?<p className="mt-2 text-sm"><strong>{t("notes")}</strong> {i.payload.reviewer_notes}</p>:null}{i.candidate_entity_id?<p className="mt-2 text-sm text-amber-800">{t("possibleDuplicate",{id:i.candidate_entity_id,score:i.match_score})}</p>:null}</div><time className="text-sm">{new Date(i.created_at).toLocaleDateString(getIntlLocale(locale))}</time></div>{i.status==="PENDING"||i.status==="NEEDS_CHANGES"?<div className="mt-4 flex flex-wrap gap-2"><AppButton loading={busy===i.id} onClick={()=>void act(i,"APPROVE")}>{t("actions.approve")}</AppButton><AppButton variant="outline" onClick={()=>void act(i,"EDIT_APPROVE")}>{t("actions.editApprove")}</AppButton><AppButton variant="outline" onClick={()=>void act(i,"MERGE")}>{t("actions.merge")}</AppButton><AppButton variant="outline" onClick={()=>void act(i,"NEEDS_CHANGES")}>{t("actions.requestChanges")}</AppButton><AppButton variant="ghost" onClick={()=>void act(i,"REJECT")}>{t("actions.reject")}</AppButton></div>:null}</AppCard>)}</div>{!error&&items.length===0?<AppCard><p>{t("empty")}</p></AppCard>:null}</section>}
