import { NextRequest,NextResponse } from "next/server";
import { requireAdminUser } from "@/lib/apiAuth";
import { findDuplicates,parseContribution } from "@/lib/catalogContributions";
import { getServiceClient } from "@/lib/supabaseServer";
import type { CatalogEntityType } from "@/lib/catalogSearch";
export const runtime="nodejs";
function responseError(e:unknown){const m=e instanceof Error?e.message:"UNKNOWN";return NextResponse.json({error:m},{status:/JWT|Bearer/.test(m)?401:m==="Forbidden"?403:400});}
export async function GET(req:NextRequest){try{await requireAdminUser(req);const url=new URL(req.url),status=url.searchParams.get("status"),entity=url.searchParams.get("entity_type");let query=getServiceClient().from("catalog_review_queue").select("id,entity_type,payload,status,created_at,updated_at,submitted_by,candidate_entity_id,match_score,reasons,user_message,moderation_note,canonical_record_id").eq("source","user_submission").order("created_at",{ascending:false}).limit(100);if(status)query=query.eq("status",status);if(entity)query=query.eq("entity_type",entity);const {data,error}=await query;if(error)throw error;return NextResponse.json({submissions:data});}catch(e){return responseError(e);}}
export async function PATCH(req:NextRequest){try{const admin=await requireAdminUser(req);const body=await req.json() as Record<string,unknown>;const action=String(body.action||"").toUpperCase();const db=getServiceClient();let payload:unknown=null;if(body.data&&body.entity_type)payload=parseContribution(body.entity_type as CatalogEntityType,body.data);if(action==="APPROVE"&&payload){const duplicates=await findDuplicates(body.entity_type as CatalogEntityType,payload as ReturnType<typeof parseContribution>);if(duplicates[0]?.score>=90&&!body.confirm_duplicate)return NextResponse.json({error:"DUPLICATE_RECHECK",duplicates},{status:409});}const {data,error}=await db.rpc("moderate_catalog_submission",{p_submission_id:String(body.id),p_action:action,p_payload:payload,p_canonical_record_id:body.canonical_record_id||null,p_moderation_note:body.moderation_note||null,p_user_message:body.user_message||null,p_reviewer_id:admin.userId});if(error)throw error;return NextResponse.json({canonical_record_id:data});}catch(e){return responseError(e);}}
