export type GeoRegistry = {
  [countryCode: string]: {
    label: string;
    regions: Array<{ name: string; provinces?: string[] }>;
  };
};

export const GEO: GeoRegistry = {
  it: {
    label: "Italia",
    regions: [
      {
        name: "Abruzzo",
        provinces: ["L'Aquila", "Chieti", "Pescara", "Teramo"],
      },
      { name: "Basilicata", provinces: ["Matera", "Potenza"] },
      {
        name: "Calabria",
        provinces: [
          "Catanzaro",
          "Cosenza",
          "Crotone",
          "Reggio Calabria",
          "Vibo Valentia",
        ],
      },
      {
        name: "Campania",
        provinces: ["Avellino", "Benevento", "Caserta", "Napoli", "Salerno"],
      },
      {
        name: "Emilia-Romagna",
        provinces: [
          "Bologna",
          "Ferrara",
          "Forlì-Cesena",
          "Modena",
          "Parma",
          "Piacenza",
          "Ravenna",
          "Reggio Emilia",
          "Rimini",
        ],
      },
      {
        name: "Friuli-Venezia Giulia",
        provinces: ["Gorizia", "Pordenone", "Trieste", "Udine"],
      },
      {
        name: "Lazio",
        provinces: ["Frosinone", "Latina", "Rieti", "Roma", "Viterbo"],
      },
      {
        name: "Liguria",
        provinces: ["Genova", "Imperia", "La Spezia", "Savona"],
      },
      {
        name: "Lombardia",
        provinces: [
          "Bergamo",
          "Brescia",
          "Como",
          "Cremona",
          "Lecco",
          "Lodi",
          "Mantova",
          "Milano",
          "Monza e della Brianza",
          "Pavia",
          "Sondrio",
          "Varese",
        ],
      },
      {
        name: "Marche",
        provinces: [
          "Ancona",
          "Ascoli Piceno",
          "Fermo",
          "Macerata",
          "Pesaro e Urbino",
        ],
      },
      { name: "Molise", provinces: ["Campobasso", "Isernia"] },
      {
        name: "Piemonte",
        provinces: [
          "Alessandria",
          "Asti",
          "Biella",
          "Cuneo",
          "Novara",
          "Torino",
          "Verbano-Cusio-Ossola",
          "Vercelli",
        ],
      },
      {
        name: "Puglia",
        provinces: [
          "Bari",
          "Barletta-Andria-Trani",
          "Brindisi",
          "Foggia",
          "Lecce",
          "Taranto",
        ],
      },
      {
        name: "Sardegna",
        provinces: ["Cagliari", "Nuoro", "Oristano", "Sassari", "Sud Sardegna"],
      },
      {
        name: "Sicilia",
        provinces: [
          "Agrigento",
          "Caltanissetta",
          "Catania",
          "Enna",
          "Messina",
          "Palermo",
          "Ragusa",
          "Siracusa",
          "Trapani",
        ],
      },
      {
        name: "Toscana",
        provinces: [
          "Arezzo",
          "Firenze",
          "Grosseto",
          "Livorno",
          "Lucca",
          "Massa-Carrara",
          "Pisa",
          "Pistoia",
          "Prato",
          "Siena",
        ],
      },
      { name: "Trentino-Alto Adige", provinces: ["Bolzano", "Trento"] },
      { name: "Umbria", provinces: ["Perugia", "Terni"] },
      { name: "Valle d'Aosta", provinces: ["Aosta"] },
      {
        name: "Veneto",
        provinces: [
          "Belluno",
          "Padova",
          "Rovigo",
          "Treviso",
          "Venezia",
          "Verona",
          "Vicenza",
        ],
      },
    ],
  },
  mx: {
    label: "Messico",
    regions: [
      { name: "Aguascalientes" },
      { name: "Baja California" },
      {
        name: "Baja California Sur",
        provinces: ["La Paz", "Los Cabos", "Comondú", "Loreto", "Mulegé"],
      },
      { name: "Campeche" },
      { name: "Chiapas" },
      { name: "Chihuahua" },
      {
        name: "Ciudad de México",
        provinces: [
          "Álvaro Obregón",
          "Azcapotzalco",
          "Benito Juárez",
          "Coyoacán",
          "Cuajimalpa de Morelos",
          "Cuauhtémoc",
          "Gustavo A. Madero",
          "Iztacalco",
          "Iztapalapa",
          "La Magdalena Contreras",
          "Miguel Hidalgo",
          "Milpa Alta",
          "Tláhuac",
          "Tlalpan",
          "Venustiano Carranza",
          "Xochimilco",
        ],
      },
      { name: "Coahuila" },
      { name: "Colima" },
      { name: "Durango" },
      {
        name: "Guanajuato",
        provinces: [
          "San Miguel de Allende",
          "Guanajuato",
          "León",
          "Irapuato",
          "Celaya",
          "Salamanca",
        ],
      },
      {
        name: "Guerrero",
        provinces: [
          "Acapulco de Juárez",
          "Taxco de Alarcón",
          "Chilpancingo de los Bravo",
          "Zihuatanejo de Azueta",
        ],
      },
      {
        name: "Hidalgo",
        provinces: [
          "Pachuca de Soto",
          "Mineral de la Reforma",
          "Tulancingo de Bravo",
          "Huasca de Ocampo",
        ],
      },
      {
        name: "Jalisco",
        provinces: [
          "Guadalajara",
          "Zapopan",
          "Tlaquepaque",
          "Tlajomulco de Zúñiga",
          "Puerto Vallarta",
          "Tepatitlán de Morelos",
        ],
      },
      {
        name: "México",
        provinces: [
          "Toluca",
          "Metepec",
          "Naucalpan de Juárez",
          "Tlalnepantla de Baz",
          "Ecatepec de Morelos",
          "Nezahualcóyotl",
          "Valle de Bravo",
        ],
      },
      {
        name: "Michoacán",
        provinces: ["Morelia", "Pátzcuaro", "Uruapan", "Zamora"],
      },
      {
        name: "Morelos",
        provinces: ["Cuernavaca", "Tepoztlán", "Jiutepec", "Tlayacapan"],
      },
      {
        name: "Nayarit",
        provinces: [
          "Bahía de Banderas",
          "Tepic",
          "Compostela",
          "San Blas",
          "Sayulita (Bahía de Banderas)",
        ],
      },
      {
        name: "Nuevo León",
        provinces: [
          "Monterrey",
          "San Pedro Garza García",
          "San Nicolás de los Garza",
          "Guadalupe",
          "Apodaca",
          "Santa Catarina",
        ],
      },
      {
        name: "Oaxaca",
        provinces: [
          "Oaxaca de Juárez",
          "Santa María Huatulco",
          "San Pedro Mixtepec",
          "Puerto Escondido",
          "San Cristóbal de las Casas",
        ],
      },
      {
        name: "Puebla",
        provinces: [
          "Puebla",
          "San Andrés Cholula",
          "San Pedro Cholula",
          "Atlixco",
        ],
      },
      {
        name: "Querétaro",
        provinces: [
          "Querétaro",
          "San Juan del Río",
          "Tequisquiapan",
          "Ezequiel Montes (Bernal)",
        ],
      },
      {
        name: "Quintana Roo",
        provinces: [
          "Benito Juárez (Cancún)",
          "Solidaridad (Playa del Carmen)",
          "Tulum",
          "Cozumel",
          "Isla Mujeres",
          "Puerto Morelos",
        ],
      },
      { name: "San Luis Potosí" },
      {
        name: "Sinaloa",
        provinces: ["Mazatlán", "Culiacán", "Los Mochis (Ahome)"],
      },
      { name: "Sonora" },
      { name: "Tabasco" },
      { name: "Tamaulipas" },
      { name: "Tlaxcala" },
      {
        name: "Veracruz",
        provinces: ["Veracruz", "Xalapa", "Boca del Río", "Coatzacoalcos"],
      },
      {
        name: "Yucatán",
        provinces: ["Mérida", "Valladolid", "Progreso", "Tizimín", "Izamal"],
      },
      { name: "Zacatecas" },
    ],
  },
  es: {
    label: "Spagna",
    regions: [
      {
        name: "Andalucía",
        provinces: [
          "Almería",
          "Cádiz",
          "Córdoba",
          "Granada",
          "Huelva",
          "Jaén",
          "Málaga",
          "Sevilla",
        ],
      },
      { name: "Aragón", provinces: ["Huesca", "Teruel", "Zaragoza"] },
      { name: "Asturias", provinces: ["Asturias"] },
      { name: "Islas Baleares", provinces: ["Illes Balears"] },
      { name: "Canarias", provinces: ["Las Palmas", "Santa Cruz de Tenerife"] },
      { name: "Cantabria", provinces: ["Cantabria"] },
      {
        name: "Castilla-La Mancha",
        provinces: [
          "Albacete",
          "Ciudad Real",
          "Cuenca",
          "Guadalajara",
          "Toledo",
        ],
      },
      {
        name: "Castilla y León",
        provinces: [
          "Ávila",
          "Burgos",
          "León",
          "Palencia",
          "Salamanca",
          "Segovia",
          "Soria",
          "Valladolid",
          "Zamora",
        ],
      },
      {
        name: "Cataluña",
        provinces: ["Barcelona", "Girona", "Lleida", "Tarragona"],
      },
      {
        name: "Comunidad Valenciana",
        provinces: [
          "Alicante/Alacant",
          "Castellón/Castelló",
          "Valencia/València",
        ],
      },
      { name: "Extremadura", provinces: ["Badajoz", "Cáceres"] },
      {
        name: "Galicia",
        provinces: ["A Coruña", "Lugo", "Ourense", "Pontevedra"],
      },
      { name: "La Rioja", provinces: ["La Rioja"] },
      { name: "Madrid", provinces: ["Madrid"] },
      { name: "Murcia", provinces: ["Murcia"] },
      { name: "Navarra", provinces: ["Navarra"] },
      { name: "País Vasco", provinces: ["Álava/Araba", "Gipuzkoa", "Bizkaia"] },
      { name: "Ceuta", provinces: ["Ceuta"] },
      { name: "Melilla", provinces: ["Melilla"] },
    ],
  },
  fr: {
    label: "Francia",
    regions: [
      {
        name: "Auvergne-Rhône-Alpes",
        provinces: [
          "Ain",
          "Allier",
          "Ardèche",
          "Cantal",
          "Drôme",
          "Isère",
          "Loire",
          "Haute-Loire",
          "Puy-de-Dôme",
          "Rhône",
          "Savoie",
          "Haute-Savoie",
        ],
      },
      {
        name: "Bourgogne-Franche-Comté",
        provinces: [
          "Côte-d'Or",
          "Doubs",
          "Haute-Saône",
          "Jura",
          "Nièvre",
          "Saône-et-Loire",
          "Territoire de Belfort",
          "Yonne",
        ],
      },
      {
        name: "Bretagne",
        provinces: [
          "Côtes-d'Armor",
          "Finistère",
          "Ille-et-Vilaine",
          "Morbihan",
        ],
      },
      {
        name: "Centre-Val de Loire",
        provinces: [
          "Cher",
          "Eure-et-Loir",
          "Indre",
          "Indre-et-Loire",
          "Loir-et-Cher",
          "Loiret",
        ],
      },
      { name: "Corse", provinces: ["Corse-du-Sud", "Haute-Corse"] },
      {
        name: "Grand Est",
        provinces: [
          "Ardennes",
          "Aube",
          "Marne",
          "Haute-Marne",
          "Meurthe-et-Moselle",
          "Meuse",
          "Moselle",
          "Bas-Rhin",
          "Haut-Rhin",
          "Vosges",
        ],
      },
      {
        name: "Hauts-de-France",
        provinces: ["Aisne", "Nord", "Oise", "Pas-de-Calais", "Somme"],
      },
      {
        name: "Île-de-France",
        provinces: [
          "Paris",
          "Seine-et-Marne",
          "Yvelines",
          "Essonne",
          "Hauts-de-Seine",
          "Seine-Saint-Denis",
          "Val-de-Marne",
          "Val-d'Oise",
        ],
      },
      {
        name: "Normandie",
        provinces: ["Calvados", "Eure", "Manche", "Orne", "Seine-Maritime"],
      },
      {
        name: "Nouvelle-Aquitaine",
        provinces: [
          "Charente",
          "Charente-Maritime",
          "Corrèze",
          "Creuse",
          "Dordogne",
          "Gironde",
          "Landes",
          "Lot-et-Garonne",
          "Pyrénées-Atlantiques",
          "Deux-Sèvres",
          "Vienne",
          "Haute-Vienne",
        ],
      },
      {
        name: "Occitanie",
        provinces: [
          "Ariège",
          "Aude",
          "Aveyron",
          "Gard",
          "Haute-Garonne",
          "Gers",
          "Hérault",
          "Lot",
          "Lozère",
          "Hautes-Pyrénées",
          "Pyrénées-Orientales",
          "Tarn",
          "Tarn-et-Garonne",
        ],
      },
      {
        name: "Pays de la Loire",
        provinces: [
          "Loire-Atlantique",
          "Maine-et-Loire",
          "Mayenne",
          "Sarthe",
          "Vendée",
        ],
      },
      {
        name: "Provence-Alpes-Côte d'Azur",
        provinces: [
          "Alpes-de-Haute-Provence",
          "Hautes-Alpes",
          "Alpes-Maritimes",
          "Bouches-du-Rhône",
          "Var",
          "Vaucluse",
        ],
      },
      { name: "Guadeloupe", provinces: ["Guadeloupe"] },
      { name: "Guyane", provinces: ["Guyane"] },
      { name: "La Réunion", provinces: ["La Réunion"] },
      { name: "Martinique", provinces: ["Martinique"] },
    ],
  },
  in: {
    label: "India",
    regions: [
      { name: "Andhra Pradesh" },
      { name: "Arunachal Pradesh" },
      { name: "Assam" },
      { name: "Bihar" },
      { name: "Chhattisgarh" },
      { name: "Goa" },
      { name: "Gujarat" },
      { name: "Haryana" },
      { name: "Himachal Pradesh" },
      { name: "Jharkhand" },
      { name: "Karnataka" },
      { name: "Kerala" },
      { name: "Madhya Pradesh" },
      { name: "Maharashtra" },
      { name: "Manipur" },
      { name: "Meghalaya" },
      { name: "Mizoram" },
      { name: "Nagaland" },
      { name: "Odisha" },
      { name: "Punjab" },
      { name: "Rajasthan" },
      { name: "Sikkim" },
      { name: "Tamil Nadu" },
      { name: "Telangana" },
      { name: "Tripura" },
      { name: "Uttar Pradesh" },
      { name: "Uttarakhand" },
      { name: "West Bengal" },
      { name: "Andaman and Nicobar Islands" },
      { name: "Chandigarh" },
      { name: "Dadra and Nagar Haveli and Daman and Diu" },
      { name: "Delhi" },
      { name: "Jammu and Kashmir" },
      { name: "Ladakh" },
      { name: "Lakshadweep" },
      { name: "Puducherry" },
    ],
  },
  jp: {
    label: "Giappone",
    regions: [
      { name: "Hokkaidō" },
      { name: "Aomori" },
      { name: "Iwate" },
      { name: "Miyagi" },
      { name: "Akita" },
      { name: "Yamagata" },
      { name: "Fukushima" },
      { name: "Ibaraki" },
      { name: "Tochigi" },
      { name: "Gunma" },
      { name: "Saitama" },
      { name: "Chiba" },
      { name: "Tōkyō" },
      { name: "Kanagawa" },
      { name: "Niigata" },
      { name: "Toyama" },
      { name: "Ishikawa" },
      { name: "Fukui" },
      { name: "Yamanashi" },
      { name: "Nagano" },
      { name: "Gifu" },
      { name: "Shizuoka" },
      { name: "Aichi" },
      { name: "Mie" },
      { name: "Shiga" },
      { name: "Kyōto" },
      { name: "Ōsaka" },
      { name: "Hyōgo" },
      { name: "Nara" },
      { name: "Wakayama" },
      { name: "Tottori" },
      { name: "Shimane" },
      { name: "Okayama" },
      { name: "Hiroshima" },
      { name: "Yamaguchi" },
      { name: "Tokushima" },
      { name: "Kagawa" },
      { name: "Ehime" },
      { name: "Kōchi" },
      { name: "Fukuoka" },
      { name: "Saga" },
      { name: "Nagasaki" },
      { name: "Kumamoto" },
      { name: "Ōita" },
      { name: "Miyazaki" },
      { name: "Kagoshima" },
      { name: "Okinawa" },
    ],
  },
  gb: {
    label: "Regno Unito",
    regions: [
      { name: "England", provinces: [] },
      { name: "Scotland", provinces: [] },
      { name: "Wales", provinces: [] },
      { name: "Northern Ireland", provinces: [] },
    ],
  },
  ae: {
    label: "Emirati Arabi Uniti",
    regions: [
      { name: "Abu Dhabi" },
      { name: "Dubai" },
      { name: "Sharjah" },
      { name: "Ajman" },
      { name: "Umm Al Quwain" },
      { name: "Ras Al Khaimah" },
      { name: "Fujairah" },
    ],
  },
  us: {
    label: "Stati Uniti",
    regions: [
      { name: "Alabama" },
      { name: "Alaska" },
      { name: "Arizona" },
      { name: "Arkansas" },
      { name: "California" },
      { name: "Colorado" },
      { name: "Connecticut" },
      { name: "Delaware" },
      { name: "District of Columbia" },
      { name: "Florida" },
      { name: "Georgia" },
      { name: "Hawaii" },
      { name: "Idaho" },
      { name: "Illinois" },
      { name: "Indiana" },
      { name: "Iowa" },
      { name: "Kansas" },
      { name: "Kentucky" },
      { name: "Louisiana" },
      { name: "Maine" },
      { name: "Maryland" },
      { name: "Massachusetts" },
      { name: "Michigan" },
      { name: "Minnesota" },
      { name: "Mississippi" },
      { name: "Missouri" },
      { name: "Montana" },
      { name: "Nebraska" },
      { name: "Nevada" },
      { name: "New Hampshire" },
      { name: "New Jersey" },
      { name: "New Mexico" },
      { name: "New York" },
      { name: "North Carolina" },
      { name: "North Dakota" },
      { name: "Ohio" },
      { name: "Oklahoma" },
      { name: "Oregon" },
      { name: "Pennsylvania" },
      { name: "Rhode Island" },
      { name: "South Carolina" },
      { name: "South Dakota" },
      { name: "Tennessee" },
      { name: "Texas" },
      { name: "Utah" },
      { name: "Vermont" },
      { name: "Virginia" },
      { name: "Washington" },
      { name: "West Virginia" },
      { name: "Wisconsin" },
      { name: "Wyoming" },
    ],
  },
  br: {
    label: "Brasile",
    regions: [
      { name: "Acre" },
      { name: "Alagoas" },
      { name: "Amapá" },
      { name: "Amazonas" },
      { name: "Bahia" },
      { name: "Ceará" },
      { name: "Distrito Federal" },
      { name: "Espírito Santo" },
      { name: "Goiás" },
      { name: "Maranhão" },
      { name: "Mato Grosso" },
      { name: "Mato Grosso do Sul" },
      { name: "Minas Gerais" },
      { name: "Pará" },
      { name: "Paraíba" },
      { name: "Paraná" },
      { name: "Pernambuco" },
      { name: "Piauí" },
      { name: "Rio de Janeiro" },
      { name: "Rio Grande do Norte" },
      { name: "Rio Grande do Sul" },
      { name: "Rondônia" },
      { name: "Roraima" },
      { name: "Santa Catarina" },
      { name: "São Paulo" },
      { name: "Sergipe" },
      { name: "Tocantins" },
    ],
  },
  ca: {
    label: "Canada",
    regions: [
      { name: "Alberta" },
      { name: "British Columbia" },
      { name: "Manitoba" },
      { name: "New Brunswick" },
      { name: "Newfoundland and Labrador" },
      { name: "Northwest Territories" },
      { name: "Nova Scotia" },
      { name: "Nunavut" },
      { name: "Ontario" },
      { name: "Prince Edward Island" },
      { name: "Quebec" },
      { name: "Saskatchewan" },
      { name: "Yukon" },
    ],
  },
  de: {
    label: "Germania",
    regions: [
      { name: "Baden-Württemberg" },
      { name: "Bavaria" },
      { name: "Berlin" },
      { name: "Brandenburg" },
      { name: "Bremen" },
      { name: "Hamburg" },
      { name: "Hesse" },
      { name: "Lower Saxony" },
      { name: "Mecklenburg-Vorpommern" },
      { name: "North Rhine-Westphalia" },
      { name: "Rhineland-Palatinate" },
      { name: "Saarland" },
      { name: "Saxony" },
      { name: "Saxony-Anhalt" },
      { name: "Schleswig-Holstein" },
      { name: "Thuringia" },
    ],
  },
  id: {
    label: "Indonesia",
    regions: [
      { name: "Aceh" },
      { name: "Bali" },
      { name: "Bangka Belitung" },
      { name: "Banten" },
      { name: "Bengkulu" },
      { name: "Central Java" },
      { name: "Central Kalimantan" },
      { name: "Central Sulawesi" },
      { name: "East Java" },
      { name: "East Kalimantan" },
      { name: "East Nusa Tenggara" },
      { name: "Gorontalo" },
      { name: "Jakarta" },
      { name: "Jambi" },
      { name: "Lampung" },
      { name: "Maluku" },
      { name: "North Kalimantan" },
      { name: "North Maluku" },
      { name: "North Sulawesi" },
      { name: "North Sumatra" },
      { name: "Papua" },
      { name: "Riau" },
      { name: "Riau Islands" },
      { name: "Southeast Sulawesi" },
      { name: "South Kalimantan" },
      { name: "South Sulawesi" },
      { name: "South Sumatra" },
      { name: "West Java" },
      { name: "West Kalimantan" },
      { name: "West Nusa Tenggara" },
      { name: "West Papua" },
      { name: "West Sulawesi" },
      { name: "West Sumatra" },
      { name: "Yogyakarta" },
    ],
  },
  cn: {
    label: "Cina",
    regions: [{ name: "China" }],
  },
  us: {
    label: "Stati Uniti",
    regions: [{ name: "USA" }],
  },
  fr: {
    label: "Francia",
    regions: [{ name: "France" }],
  },
  es: {
    label: "Spagna",
    regions: [{ name: "España" }],
  },
  pt: {
    label: "Portogallo",
    regions: [{ name: "Portugal" }],
  },
  br: {
    label: "Brasile",
    regions: [{ name: "Brasil" }],
  },
  jp: {
    label: "Giappone",
    regions: [{ name: "Japan" }],
  },
  ae: {
    label: "Emirati Arabi Uniti",
    regions: [{ name: "Emirates" }],
  },
  id: {
    label: "Indonesia",
    regions: [{ name: "Indonesia" }],
  },
  in: {
    label: "India",
    regions: [{ name: "India" }],
  },
  ca: {
    label: "Canada",
    regions: [{ name: "Canada" }],
  },
  sa: {
    label: "Arabia Saudita",
    regions: [
      { name: "Al Bahah" },
      { name: "Al Jawf" },
      { name: "Al Madinah" },
      { name: "Al-Qassim" },
      { name: "Asir" },
      { name: "Eastern Province" },
      { name: "Ha'il" },
      { name: "Jazan" },
      { name: "Makkah" },
      { name: "Najran" },
      { name: "Northern Borders" },
      { name: "Riyadh" },
      { name: "Tabuk" },
    ],
  },
};

export function getUserCountrySafe(): string {
  try {
    const cookieCountry =
      typeof document !== "undefined"
        ? document.cookie.match(/(?:^|; )country=([^;]+)/)?.[1]
        : null;
    const lsCountry =
      typeof window !== "undefined" ? localStorage.getItem("country") : null;
    return (cookieCountry || lsCountry || "it").toLowerCase();
  } catch {
    return "it";
  }
}
