export const flags = {
  en_ui: true,
  es_ui: false,
  country_mexico: true,
  country_india: false,
  ai_suggestions: false,
  payments_stripe: true,
  enable_wedding: true,
  enable_baptism: true,
  enable_communion: true,
  enable_confirmation: true,
  enable_graduation: true,
  enable_anniversary: true,
  enable_gender_reveal: true,
  enable_birthday: true,
  enable_fifty: true,
  enable_retirement: true,
  enable_eighteenth: true,
  enable_baby_shower: true,
  enable_engagement_party: true,
  enable_proposal: true,
  enable_bar_mitzvah: true,
  enable_quinceanera: true,
  enable_corporate: true,
  enable_charity_gala: true,
} as const;

export type FeatureFlags = typeof flags;
