"use client";
import { getBrowserClient } from "@/lib/supabaseBrowser";
import { useLocale, useTranslations } from "next-intl";
import { useEffect, useRef, useState } from "react";

type Member={id:string;role:"owner"|"partner";status:string};
type Invitation={id:string;invited_email_normalized:string;status:string;expires_at:string;delivery_status:string};
export default function PartnerLifecycleSection(){
 const locale=useLocale(),t=useTranslations("runtimeUi.partnerLifecycle"),[members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[role,setRole]=useState<string>(""),[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null),alert=useRef<HTMLParagraphElement>(null);
 async function request(path:string,init?:RequestInit){const {data}=await getBrowserClient().auth.getSession();if(!data.session)throw new Error("NOT_AUTHENTICATED");const r=await fetch(path,{...init,headers:{Authorization:`Bearer ${data.session.access_token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const json=await r.json().catch(()=>({}));if(!r.ok)throw new Error(json.error||"REQUEST_FAILED");return json;}
 async function load(){try{const m=await request("/api/my/event-members");setMembers(m.members);setRole(m.accessRole);if(m.accessRole==="owner"){const i=await request("/api/my/event-invitations");setInvites(i.invitations);}}catch(e){setError(e instanceof Error?e.message:"REQUEST_FAILED");}}
 useEffect(()=>{void load();},[]);useEffect(()=>{if(error)alert.current?.focus();},[error]);
 async function act(fn:()=>Promise<unknown>,success:string){setBusy(true);setError(null);try{await fn();setMessage(t(success));await load();}catch(e){setError(e instanceof Error?e.message:"REQUEST_FAILED");}finally{setBusy(false);}}
 const partner=members.find(m=>m.role==="partner"),pending=invites.find(i=>i.status==="pending"),latest=invites[0];
 return <section className="mt-8 space-y-4 border-t pt-6" aria-labelledby="partner-title"><h2 id="partner-title" className="text-xl font-semibold">{t("manageTitle")}</h2>
 {role==="partner"?<><p>{t("activeAsPartner")}</p><button className="app-button app-button-ghost text-red-700" disabled={busy} onClick={()=>{if(confirm(t("confirmLeave")))void act(()=>request("/api/my/event-members/leave",{method:"POST"}),"left").then(()=>window.location.replace(`/${locale}/select-event`));}}>{t("leave")}</button></>:role==="owner"?<>
 {partner?<><p role="status">{t("activePartner")}</p><button className="app-button app-button-ghost text-red-700" disabled={busy} onClick={()=>{if(confirm(t("confirmRemove")))void act(()=>request(`/api/my/event-members/${partner.id}`,{method:"DELETE"}),"removed");}}>{t("remove")}</button></>:pending?<><p role="status">{t(pending.delivery_status==="failed"?"deliveryFailed":"pending",{email:pending.invited_email_normalized})}</p><div className="flex flex-wrap gap-2"><button className="app-button app-button-primary" disabled={busy} onClick={()=>void act(()=>request("/api/my/event-invitations",{method:"PATCH",body:JSON.stringify({invitationId:pending.id})}),"resent")}>{t("resend")}</button><button className="app-button app-button-ghost" disabled={busy} onClick={()=>{if(confirm(t("confirmCancel")))void act(()=>request(`/api/my/event-invitations/${pending.id}`,{method:"DELETE"}),"cancelled");}}>{t("cancel")}</button></div></>:<><p>{latest?.status==="expired"?t("states.expired"):latest?.status==="rejected"?t("states.rejected"):t("none")}</p><label className="block">{t("partnerEmail")}<input className="mt-1 block w-full border px-3 py-2" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="app-button app-button-primary" disabled={busy||!email} onClick={()=>void act(()=>request("/api/my/event-invitations",{method:"POST",body:JSON.stringify({email})}),"sent")}>{t("invite")}</button></>}</>:<p role="status">{t("loading")}</p>}
 {message&&<p role="status">{message}</p>}{error&&<p ref={alert} tabIndex={-1} role="alert">{t("genericError",{code:error})}</p>}</section>;
}
