import assert from "node:assert/strict";
import test from "node:test";
import { normalizeChurch } from "./church-import-core.mjs";
import { normalizeLocation } from "./location-import-core.mjs";
import { normalizeSupplier } from "./supplier-import-core.mjs";
import { normalizeText, normalizeUrl, rawFingerprint } from "./catalog-import-core.mjs";
import { formatImportReport, MemoryCatalogRepository, mergeWithoutDataLoss, runCatalogIngestion } from "./common-catalog-pipeline.mjs";

const source = { type: "official_site", name: "Controlled fixture", url: "https://example.test/catalog" };
const base = { name: "  Villa Èlite  ", address_line: " Via Roma 1 ", city: "Agrigento", province: "AG", region: "Sicilia", country_code: "IT", source: "official_site", source_url: "https://EXAMPLE.test/item/#about", external_id: "fixture-1" };

test("normalizes church, location and supplier with the common identity fields", () => {
  for (const record of [normalizeChurch(base), normalizeLocation(base), normalizeSupplier({ ...base, category: "photographer" })]) {
    assert.equal(record.normalized_name, "villa elite"); assert.equal(record.slug, "villa-elite"); assert.equal(record.country_code, "it"); assert.equal(record.source_url, "https://example.test/item");
  }
});
test("normalization is idempotent and Unicode-safe", () => { const once = normalizeChurch({ ...base, name: "Sant’Àgata\u00a0  Città" }); const twice = normalizeChurch(once); assert.deepEqual(twice, once); assert.equal(normalizeText("Città"), "citta"); });
test("URL canonicalization is deterministic and rejects unsafe schemes", () => { assert.equal(normalizeUrl("HTTPS://EXAMPLE.COM/a/?b=2&a=1#x"), "https://example.com/a?a=1&b=2"); assert.equal(normalizeUrl("javascript:alert(1)"), null); });
test("raw provenance fingerprint is stable across object key order", () => { assert.equal(rawFingerprint({ a: 1, b: 2 }), rawFingerprint({ b: 2, a: 1 })); });
test("malformed records are rejected with blocking and warning validation", async () => { const report = await runCatalogIngestion({ entityType: "church", source, records: [{ name: "", country_code: "Italy" }], repository: new MemoryCatalogRepository() }); assert.equal(report.invalid, 1); assert.equal(report.rejected, 1); assert.ok(report.records[0].issues.some((issue) => issue.severity === "blocking")); });
test("strong source identity updates idempotently and records provenance", async () => { const repository = new MemoryCatalogRepository(); const first = await runCatalogIngestion({ entityType: "location", source, records: [base], repository, dryRun: false }); const second = await runCatalogIngestion({ entityType: "location", source, records: [base], repository, dryRun: false }); assert.equal(first.inserted, 1); assert.equal(second.updated, 1); assert.equal(repository.rows.location.length, 1); assert.equal(repository.provenance.length, 1); });
test("strong phone duplicate links safely across sources", async () => { const existing = normalizeChurch({ ...base, id: "church-1", phone: "+39 0922 123456" }); const repository = new MemoryCatalogRepository({ church: [existing] }); const report = await runCatalogIngestion({ entityType: "church", source: { type: "admin_import", name: "Admin" }, records: [{ ...base, source: "admin_import", external_id: "other", phone: "+39 0922 123456" }], repository }); assert.equal(report.updated, 1); assert.equal(report.duplicates, 1); });
test("weak same-name candidate is routed to review, not merged", async () => { const existing = normalizeLocation({ ...base, id: "location-1", address_line: "Via Uno 1", external_id: "old" }); const repository = new MemoryCatalogRepository({ location: [existing] }); const report = await runCatalogIngestion({ entityType: "location", source, records: [{ ...base, address_line: "Via Due 2", external_id: "new" }], repository }); assert.equal(report.review, 1); assert.equal(report.updated, 0); });
test("different identity is not a duplicate", async () => { const repository = new MemoryCatalogRepository({ supplier: [normalizeSupplier({ ...base, id: "s1", category: "photographer" })] }); const report = await runCatalogIngestion({ entityType: "supplier", source, records: [{ ...base, name: "Fiori Blu", city: "Licata", category: "florist", external_id: "s2" }], repository }); assert.equal(report.inserted, 1); assert.equal(report.duplicates, 0); });
test("a lower-confidence import cannot downgrade verified data or erase fields", () => { const merged = mergeWithoutDataLoss({ id: "1", website: "https://official.test/", verification_status: "VERIFIED", verified: true, confidence_score: 90, last_verified_at: "2026-01-01" }, { website: null, verification_status: "TO_CHECK", verified: false, confidence_score: 20 }); assert.equal(merged.website, "https://official.test/"); assert.equal(merged.verification_status, "VERIFIED"); assert.equal(merged.confidence_score, 90); });
test("dry-run reports all actions without writes", async () => { const repository = new MemoryCatalogRepository(); const report = await runCatalogIngestion({ entityType: "supplier", source, records: [{ ...base, category: "photographer" }], repository, dryRun: true }); assert.equal(repository.writes, 0); assert.equal(report.inserted, 1); assert.match(formatImportReport(report), /input=1/); });
test("duplicate input is rejected without a second insert", async () => { const repository = new MemoryCatalogRepository(); const report = await runCatalogIngestion({ entityType: "church", source, records: [base, { ...base }], repository, dryRun: false }); assert.equal(report.inserted, 1); assert.equal(report.duplicates, 1); assert.equal(report.rejected, 1); });
