import { requireUser } from "@/lib/apiAuth";
import { getServiceClient } from "@/lib/supabaseServer";
import { requireServerCurrentEvent } from "@/lib/currentEvent";
import { NextRequest, NextResponse } from "next/server";
export const runtime = "nodejs";
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const STATUSES = new Set(["DISCOVERED","SAVED","CONTACTED","QUOTE_REQUESTED","QUOTE_RECEIVED","SHORTLISTED","SELECTED","REJECTED"]);
async function eventFor(userId: string) { return (await requireServerCurrentEvent(userId)).eventId; }
export async function GET(req: NextRequest) { try { const { userId } = await requireUser(req); const eventId = await eventFor(userId); if (!eventId) return NextResponse.json({ savedSuppliers: [], eventId: null }); const { data, error } = await getServiceClient().from("saved_suppliers").select("*").eq("event_id", eventId).order("created_at"); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ savedSuppliers: data || [], eventId }); } catch { return NextResponse.json({ error: "Not authenticated" }, { status: 401 }); } }
export async function POST(req: NextRequest) { try { const { userId } = await requireUser(req); const body = await req.json() as { supplier_id?: string }; if (!body.supplier_id || !UUID.test(body.supplier_id)) return NextResponse.json({ error: "Invalid supplier id" }, { status: 400 }); const eventId = await eventFor(userId); if (!eventId) return NextResponse.json({ error: "No event" }, { status: 404 }); const db = getServiceClient(); const { data: supplier } = await db.from("suppliers").select("id").eq("id", body.supplier_id).maybeSingle(); if (!supplier) return NextResponse.json({ error: "Supplier not found" }, { status: 404 }); const { data, error } = await db.from("saved_suppliers").insert({ event_id: eventId, supplier_id: body.supplier_id }).select("*").single(); if (error?.code === "23505") return NextResponse.json({ error: "Supplier already saved" }, { status: 409 }); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ savedSupplier: data }, { status: 201 }); } catch { return NextResponse.json({ error: "Not authenticated" }, { status: 401 }); } }
export async function PATCH(req: NextRequest) { try { const { userId } = await requireUser(req); const body = await req.json() as Record<string, unknown>; const id = typeof body.id === "string" ? body.id : ""; if (!UUID.test(id)) return NextResponse.json({ error: "Invalid saved supplier id" }, { status: 400 }); const eventId = await eventFor(userId); if (!eventId) return NextResponse.json({ error: "No event" }, { status: 404 }); const update: Record<string,string|boolean|number|null> = {}; if (typeof body.status === "string" && STATUSES.has(body.status)) update.status = body.status; for (const k of ["favorite","deposit_paid","contract_signed"] as const) if (typeof body[k] === "boolean") update[k] = body[k]; for (const k of ["personal_notes","contact_notes"] as const) if (typeof body[k] === "string") update[k] = body[k].trim().slice(0,4000) || null; for (const k of ["quote_amount","agreed_amount","deposit_amount","balance_amount"] as const) { if (body[k] === null) update[k] = null; else if (typeof body[k] === "number" && Number.isFinite(body[k]) && body[k] >= 0) update[k] = body[k]; } if (typeof body.currency === "string" && /^[A-Za-z]{3}$/.test(body.currency)) update.currency = body.currency.toUpperCase(); if (!Object.keys(update).length) return NextResponse.json({ error: "No valid updates" }, { status: 400 }); const { data, error } = await getServiceClient().from("saved_suppliers").update(update).eq("id", id).eq("event_id", eventId).select("*").maybeSingle(); if (error) return NextResponse.json({ error:error.message }, { status:500 }); if (!data) return NextResponse.json({ error:"Saved supplier not found" }, { status:404 }); return NextResponse.json({ savedSupplier:data }); } catch { return NextResponse.json({ error:"Not authenticated" }, { status:401 }); } }
export async function DELETE(req: NextRequest) { try { const { userId } = await requireUser(req); const id = req.nextUrl.searchParams.get("id") || ""; if (!UUID.test(id)) return NextResponse.json({ error:"Invalid saved supplier id" }, { status:400 }); const eventId = await eventFor(userId); if (!eventId) return NextResponse.json({ error:"No event" }, { status:404 }); const { data,error } = await getServiceClient().from("saved_suppliers").delete().eq("id",id).eq("event_id",eventId).select("id").maybeSingle(); if (error) return NextResponse.json({ error:error.message }, { status:500 }); if (!data) return NextResponse.json({ error:"Saved supplier not found" }, { status:404 }); return NextResponse.json({ ok:true }); } catch { return NextResponse.json({ error:"Not authenticated" }, { status:401 }); } }
