import fs from "fs";
import path from "path";

describe("Branch 43 budget apply isolation", () => {
  const route = fs.readFileSync(
    path.join(process.cwd(), "src/app/api/idea-di-budget/apply/route.ts"),
    "utf8",
  );
  const migration = fs.readFileSync(
    path.join(process.cwd(), "supabase/migrations/20260910203000_branch_43_budget_item_origin.sql"),
    "utf8",
  );

  it("replaces only rows generated by Idea di Budget", () => {
    expect(route).toContain('.eq("source", "budget_idea")');
    expect(route).toContain('source: "budget_idea"');
  });

  it("keeps pre-existing rows manual by default", () => {
    expect(migration).toContain("source text not null default 'manual'");
  });
});
