name: Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'supabase-*.sql'
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Run migrations
        run: |
          # Link to Supabase project
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          
          # Apply migrations (opzionale - automatizza l'esecuzione SQL)
          # Nota: richiede setup più avanzato con migration files organizzati
          echo "Migration files ready for manual execution in Supabase dashboard"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
