"use client";
import { getBrowserClient } from "@/lib/supabaseBrowser";
import { useLocale } from "next-intl";
import { useEffect, useState } from "react";
import { defaultLocale, isSelectableLocale, visibleLanguages } from "@/i18n/languageCapabilities";

export default function ProfilePage() {
  const locale = useLocale(); const [deleteEmail, setDeleteEmail] = useState(""); const [deletePhrase, setDeletePhrase] = useState(""); const [deletionPending, setDeletionPending] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [preferredLocale, setPreferredLocale] = useState(locale); const [busy, setBusy] = useState(true); const [message, setMessage] = useState<string | null>(null);
  async function authRequest(method: "GET" | "PATCH", body?: object) { const { data } = await getBrowserClient().auth.getSession(); if (!data.session) { window.location.replace(`/${locale}/auth`); return null; } const response = await fetch("/api/my/profile", { method, headers: { Authorization: `Bearer ${data.session.access_token}`, ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); return response.ok ? response.json() : null; }
  useEffect(() => { getBrowserClient().auth.getSession().then(async ({ data }) => { if (!data.session) { window.location.replace(`/${locale}/auth`); return; } const response = await fetch("/api/my/profile", { headers: { Authorization: `Bearer ${data.session.access_token}` } }); const profile = response.ok ? await response.json() : null; if (profile) { setName(profile.profile?.full_name || ""); setEmail(profile.email || ""); const storedLocale = profile.profile?.preferred_locale; setPreferredLocale(isSelectableLocale(storedLocale) ? storedLocale : defaultLocale); } setBusy(false); }); }, [locale]);
  async function requestDeletion() {
    if (deletePhrase !== "ELIMINA" || deleteEmail.trim().toLowerCase() !== email.trim().toLowerCase()) { setMessage("Inserisci la tua email e scrivi ELIMINA."); return; }
    setBusy(true); const { data } = await getBrowserClient().auth.getSession();
    const response = await fetch("/api/my/account-deletion", { method: "POST", headers: { Authorization: `Bearer ${data.session?.access_token || ""}`, "Content-Type": "application/json" }, body: JSON.stringify({ email: deleteEmail, confirmation: deletePhrase }) });
    setBusy(false); setDeletionPending(response.ok); setMessage(response.ok ? "Richiesta registrata. Hai 7 giorni per annullarla; il matrimonio condiviso sarà verificato prima dell'elaborazione." : "Richiesta non registrata.");
  }
  async function cancelDeletion() {
    setBusy(true); const { data } = await getBrowserClient().auth.getSession();
    const response = await fetch("/api/my/account-deletion", { method: "DELETE", headers: { Authorization: `Bearer ${data.session?.access_token || ""}` } });
    setBusy(false); if (response.ok) { setDeletionPending(false); setMessage("Richiesta annullata."); }
  }
  async function save() { setBusy(true); setMessage(null); const data = await authRequest("PATCH", { fullName: name, preferredLocale }); setBusy(false); if (data?.ok) { setMessage("Profilo aggiornato."); window.dispatchEvent(new Event("profile-updated")); } else setMessage("Non è stato possibile salvare il profilo."); }
  return <main className="mx-auto max-w-xl space-y-4"><h1 className="text-2xl font-bold">Profilo</h1><label className="block">Nome visualizzato<input className="mt-1 block w-full border px-3 py-2" autoComplete="name" maxLength={100} value={name} onChange={e => setName(e.target.value)} /></label><label className="block">Email<input className="mt-1 block w-full border bg-black/5 px-3 py-2" type="email" value={email} readOnly /></label><p className="text-xs text-muted-fg">Il cambio email non è disponibile in questo flusso.</p><label className="block">Lingua preferita<select className="mt-1 block w-full border px-3 py-2" value={preferredLocale} onChange={e => setPreferredLocale(e.target.value)}>{visibleLanguages.map(language => <option key={language.locale} value={language.locale} disabled={!language.selectable}>{language.nativeLabel}{!language.selectable ? " (In arrivo)" : ""}</option>)}</select></label><button className="app-button app-button-primary" disabled={busy || !name.trim()} onClick={save}>{busy ? "Salvataggio…" : "Salva profilo"}</button>{message && <p role="status">{message}</p>}<section className="mt-10 space-y-3 border-t pt-6" aria-labelledby="delete-account-title"><h2 id="delete-account-title" className="text-xl font-semibold text-red-700">Eliminazione account</h2><p className="text-sm text-muted-fg">La richiesta prevede 7 giorni di sicurezza. Prima dell’elaborazione viene protetto l’evento condiviso con il partner.</p><label className="block">Conferma email<input className="mt-1 block w-full border px-3 py-2" type="email" value={deleteEmail} onChange={e => setDeleteEmail(e.target.value)} /></label><label className="block">Scrivi ELIMINA<input className="mt-1 block w-full border px-3 py-2" value={deletePhrase} onChange={e => setDeletePhrase(e.target.value)} /></label>{deletionPending ? <button className="app-button app-button-ghost" disabled={busy} onClick={cancelDeletion}>Annulla richiesta</button> : <button className="app-button app-button-ghost text-red-700" disabled={busy || deletePhrase !== "ELIMINA"} onClick={requestDeletion}>Richiedi eliminazione</button>}</section></main>;
}
