"use client";
import { getBrowserClient } from "@/lib/supabaseBrowser";
import { useLocale } from "next-intl";
import { useEffect, useState } from "react";

export default function ProfilePage() {
  const locale = useLocale(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [preferredLocale, setPreferredLocale] = useState(locale); const [busy, setBusy] = useState(true); const [message, setMessage] = useState<string | null>(null);
  async function authRequest(method: "GET" | "PATCH", body?: object) { const { data } = await getBrowserClient().auth.getSession(); if (!data.session) { window.location.replace(`/${locale}/auth`); return null; } const response = await fetch("/api/my/profile", { method, headers: { Authorization: `Bearer ${data.session.access_token}`, ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined }); return response.ok ? response.json() : null; }
  useEffect(() => { getBrowserClient().auth.getSession().then(async ({ data }) => { if (!data.session) { window.location.replace(`/${locale}/auth`); return; } const response = await fetch("/api/my/profile", { headers: { Authorization: `Bearer ${data.session.access_token}` } }); const profile = response.ok ? await response.json() : null; if (profile) { setName(profile.profile?.full_name || ""); setEmail(profile.email || ""); setPreferredLocale(profile.profile?.preferred_locale || locale); } setBusy(false); }); }, [locale]);
  async function save() { setBusy(true); setMessage(null); const data = await authRequest("PATCH", { fullName: name, preferredLocale }); setBusy(false); if (data?.ok) { setMessage("Profilo aggiornato."); window.dispatchEvent(new Event("profile-updated")); } else setMessage("Non è stato possibile salvare il profilo."); }
  return <main className="mx-auto max-w-xl space-y-4"><h1 className="text-2xl font-bold">Profilo</h1><label className="block">Nome visualizzato<input className="mt-1 block w-full border px-3 py-2" autoComplete="name" maxLength={100} value={name} onChange={e => setName(e.target.value)} /></label><label className="block">Email<input className="mt-1 block w-full border bg-black/5 px-3 py-2" type="email" value={email} readOnly /></label><p className="text-xs text-muted-fg">Il cambio email non è disponibile in questo flusso.</p><label className="block">Lingua preferita<select className="mt-1 block w-full border px-3 py-2" value={preferredLocale} onChange={e => setPreferredLocale(e.target.value)}><option value="it">Italiano</option><option value="en">English</option><option value="es">Español</option></select></label><button className="app-button app-button-primary" disabled={busy || !name.trim()} onClick={save}>{busy ? "Salvataggio…" : "Salva profilo"}</button>{message && <p role="status">{message}</p>}</main>;
}
